import NftMediaCard from '../../../src/components/marketplace-details/NftMediaCard';
import Heading from '../../../src/components/marketplace-details/Heading';
import Details from '../../../src/components/marketplace-details/Details';
import { BasicLayoutWrapper } from '../../../src/utilitis/BasicLayoutWrapper';
import { Container } from '@mui/system';
import { useRouter } from 'next/router';

import { useEffect, useState } from 'react';
import Head from 'next/head';
import NftButton from '../../../src/components/nft-button/nft-button';

import axios from 'axios';

import { ethers } from 'ethers';
import PriceHistory from '../../../src/components/marketplace-details/PriceHistory';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

import MarketplaceDescription from '../../../src/components/marketplace-details/MarketplaceDescription';

const { NEXT_PUBLIC_BASE_URL } = process.env;

const Index = (props) => {
  const router = useRouter();
  const id = router.query.id;
  const [data, setData] = useState([]);
  const [data1, setData1] = useState([]);
  const [offer, setOffer] = useState([]);
  const [similarproduct, setSimilarproduct] = useState([]);
  const [provider, setProvider] = useState([]);
  const [walletAddress, setWalletAddress] = useState('');
  const [nftOwnerAddress, setNftOwnerAddress] = useState('');
  console.log(data, 'data');

  var newww = data?.data?.filter((item) => item.id == router.query.id);
  const obj1 = Object.assign({}, newww);
  console.log(obj1[0]?.id, '5555555555555');

  // response.data.find(item => item.id === id)

  const getdata = async () => {
    const response = await axios.get(
      `${NEXT_PUBLIC_BASE_URL}individualpage.json`
    );
    console.log(response, 'response');

    setData(response);
  };

  //   const getdata1 = async () => {
  //     const response = await axios.get(
  //       `${NEXT_PUBLIC_BASE_URL}api/v1/transaction?type=sell&nft=${id}`
  //     );
  //     setData1(response.data.results);
  //   };

  useEffect(() => {
    if (id) {
      getdata();
    }
  }, [id]);

  const handleclick = () => {
    router.push('/marketplace');
  };

  return (
    <>
      <Head>
        <title>Employee Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-marketplacebackground bg-no-repeat ">
        <Container>
          <div className="text-white pb-4 ">
            <ArrowBackIcon
              onClick={() => router.back()}
              sx={{
                borderRadius: '100%',
                border: 2,
                height: 25,
                width: 25,
                cursor: 'pointer',
              }}
            />
          </div>
          <div className="flex 2xs:justify-center md:justify-start gap-2">
            <div className="md:flex lg:gap-14 2xs:gap-12 md:flex-row 2xs:flex 2xs:flex-col ">
              <div className="md:max-w-[50%]">
                <NftMediaCard
                  url={obj1[0]?.metadata.animation_url}
                  imageurl={obj1[0]?.metadata.image}
                />
                <div className="2xs:hidden md:block">
                  <MarketplaceDescription
                    // properties={obj1[0]?.metadata.attributes}
                    description={obj1[0]?.metadata.description}
                  />
                </div>
              </div>

              <div className="flex flex-col gap-4 2xs:pt-4 md:pt-0">
                <Heading
                  name={obj1[0]?.name}
                  details={obj1[0]?.metadata.description}
                  emp={obj1[0]?.tokenId}
                />
                <Details
                  contractaddress={obj1[0]?.collectionItem?.dailyhours}
                  tokenid={obj1[0]?.collectionItem?.weeklyhours}
                  blockchain={obj1[0]?.collectionItem?.monthlyhours}
                />

                <div className="2xs:block md:hidden">
                  <MarketplaceDescription
                  // properties={data.data?.metadata.attributes}
                  // description={data.data?.metadata.description}
                  />
                </div>
                <div className="lg:block 2xs:hidden w-[25rem] ">
                  <PriceHistory />
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center pt-6"></div>

          <div
            className="w-[150px] mx-auto mt-[30px] mb-[30px]"
            onClick={() => handleclick()}
          >
            <NftButton text={'View More'} bgcolor={'violet'} />
          </div>
        </Container>
      </div>
    </>
  );
};

export default BasicLayoutWrapper(Index);
