import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { BasicLayoutWrapper } from '../src/utilitis/BasicLayoutWrapper';
import HeroSection from '../src/components/hero-section/hero-section';
import BannerSection from '../src/components/banner-section/banner-section';
import DiscoverSection from '../src/components/discover-section/discover-section';
import AcessSection from '../src/components/access-section-home/access-section';
import TopNft from '../src/components/top-nft-section/top-nft';

import ButtonLoading from '../src/components/button-loading/button-loading';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moon Hive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="xl:h-[100vh] 2xs:h-[35vh] xs:h-[45vh] sm:h-[60vh] lg:h-[80vh]">
        <HeroSection />
      </div>
      <div>{/* <ButtonLoading /> */}</div>
      {/* <div className="lg:px-24 lg:py-24 2xs:px-4 2xs:py-8">
        <BannerSection />
      </div> */}
      <div className="lg:py-18 2xs:py-0">
        <DiscoverSection />
      </div>
      <div className="py-2">
        <TopNft />
      </div>
      <div className="lg:py-32 2xs:py-12">
        <AcessSection />
      </div>
    </div>
  );
};

export default BasicLayoutWrapper(Home);
